AWSTemplateFormatVersion: 2010-09-09
Description: "Application resources"
Resources:
  myDynamoDB:
   Type: AWS::DynamoDB::Table
   Properties:
     AttributeDefinitions:
     - AttributeName: "id"
       AttributeType: "S"
     TableName: "csye6225"
     KeySchema: 
     - AttributeName: "id"
       KeyType: HASH
     ProvisionedThroughput: 
       ReadCapacityUnits: 5
       WriteCapacityUnits: 5

  myS3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: "csye6225-fall2018-reubenn.me.csye6225.com"

  myRDSinstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 100 
      DBInstanceClass: "db.t2.micro"
      DBInstanceIdentifier: "csye6225-fall2018"
      DBSubnetGroupName: !Ref myDBSubnetGroup
      DBName: "csye6225"
      Engine: MySQL
      MasterUsername: "csye6225master"
      MasterUserPassword: "csye6225password"
      MultiAZ: false
      PubliclyAccessible: false
      VPCSecurityGroups: 
        - sg-0e55958a35cb881e0
        
  myDBSubnetGroup: 
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: "description"
      SubnetIds: 
        - subnet-03c572dc973449013
        - subnet-0e0f03119fe9320ec

